[package]
authors = []
edition = "2021"
name = "arkc-frontend-alt"
version = "0.0.2"

[dependencies]
id-arena = "*"
parking_lot="*"
parser = {path = "../arkc-parser"}

[profile.release]
lto = true
panic = 'abort'
