[workspace]
members = [
  "ark-language-server",
  "compiler/arkc",
  "compiler/arkc-ast-lowering",
  "compiler/arkc-hir",
  "compiler/arkc-codegen-llvm",
  "compiler/arkc-frontend",
  "compiler/arkc-parser",
  "compiler/arkc-bytecode"
]
resolver = "2"
