[package]
authors = []
edition = "2021"
name = "arkc-hir"
version = "0.0.2"

[dependencies]
bincode = {version = "2.0.0-rc.3", features = ["std", "derive", "serde"]}
parser = {path = "../arkc-parser"}
serde = {version = "1.0", features = ["derive"]}

[profile.release]
lto = true
panic = 'abort'
