[package]
authors = []
edition = "2021"
name = "arkc-ast-lowering"
version = "0.0.2"

[dependencies]
parser={path = "../arkc-parser"}
arkc-hir={path = "../arkc-hir"}
bincode={version="2.0.0-rc.3", features = ["std", "derive"]}

[profile.release]
lto = true
panic = 'abort'
