[package]
name = "frontend-old"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2021"

[dependencies]
byteorder = "1.3"
jazzlight = {path = "../vm",version = "*"}
hmap = "0.1"
hashlink = "0.9"
structopt = "0.3.1"
parking_lot = "*"
